from __future__ import annotations

DECOY_THROW_DISTANCE = 96.0
DECOY_NOISE_RADIUS = 210.0
DECOY_LIFETIME_SECONDS = 2.0
DECOY_PULSE_INTERVAL_SECONDS = 0.25

SECURITY_TACTICAL_HZ = 5
SECURITY_TACTICAL_TICKS = 12
SECURITY_DOOR_LOCK_SECONDS = 3.5
SECURITY_DOOR_WARNING_SECONDS = 0.65
SECURITY_DOOR_TEAM_COOLDOWN_SECONDS = 6.0
SECURITY_DOOR_FORCED_OPEN_SECONDS = 5.0

SUPPRESSOR_AIM_SECONDS = 0.70
SUPPRESSOR_PROJECTILE_SPEED = 260.0
SUPPRESSOR_PROJECTILE_LIFETIME_SECONDS = 1.0
SUPPRESSOR_COOLDOWN_SECONDS = 2.4
SUPPRESSOR_MIN_RANGE = 96.0
SUPPRESSOR_MAX_RANGE = 240.0
SUPPRESSOR_PROJECTILE_RADIUS = 4.0

MAX_SECURITY_TARGETS = 8
MAX_RADIO_MESSAGES = 4
MAX_TEAMMATES = 4
